Fix circular dependend import
Python3 is givin an error when we try to import gumbo[1]:

    ImportError: No module named 'gumboc_tags'

This is because __init__.py is importing everything and gumboc_tags
already imported.

This patch is fixing this issue.

[1]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=789299